version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    volumes:
      - ../data/redis:/data
    restart: always

  auth_service:
    build:
      context: auth-flask-solution/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - elastic
    env_file:
      - .env
    restart: always

  api_service:
    build:
      context: fastapi-solution/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - elastic
    env_file:
      - .env
    restart: always

  etl_genres:
    image: lizatish/etl:etl_genres
    depends_on:
      - postgres
      - elastic
    env_file:
      - .env

  etl_persons:
    image: lizatish/etl:etl_persons
    depends_on:
      - postgres
      - elastic
    env_file:
      - .env

  etl_fw:
    image: lizatish/etl:etl_fw
    depends_on:
      - postgres
      - elastic
    env_file:
      - .env

  elastic:
    image: elasticsearch:7.17.5
    environment:
      ES_JAVA_OPTS: "-Xms200m -Xmx200m"
      discovery.type: single-node
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - api_service

volumes:
  esdata: